### ISSUE TITLE
How to enqueue or use jQuery with Browserify config

### ISSUE THREAD

**Issue by colorful-tones** [whatwedo/gulp-wp-theme#48]
I'm new to Browserify, and trying to grok how you'd use jQuery in this theme, and not seeing it enqueue'd or anything in source, but do see the [browserify-shim being declared](https://github.com/whatwedo/gulp-wp-theme/blob/master/package.json#L38), and kind of understand that. Do you typically enqueue the Google CDN version on entire WP site, or is there a different method of dependency management with Browserify that I'm not seeing?

Any change you could provide a quick example of how you'd use, say: [jQuery MatchHeight](http://brm.io/jquery-match-height/) in this theme with Browserify please?

Thanks for your time!

**Comment by renestalder** [comment]
Since jQuery is delivered by WordPress itself you'll mostly use this version or stick to a CDN version. In both scenarios you use functions.php to enqueue jQuery, thus making it globally available.

That's why jQuery is shimmed in the package.json of gulp-wp-theme:
```json
{
 "browserify": {
    "transform": [
      "browserify-shim"
    ]
 },
 "browserify-shim": {
    "jQuery": "global:jQuery"
  }
}
```

This way jQuery will not compile into your JavaScript files, but you are still able to reference it via require statements.

Please note, if you consume the gulp-wp-theme by npm, you may add the shimming to your own package.json.

Further information that might help you:
https://github.com/thlorenz/browserify-shim/wiki/browserify-shim-recipes

**Comment by colorful-tones** [comment]
Ok, so I was not misunderstanding, and want to further clarify that WordPress out-of-box does not automatically enqueue jQuery, but the theme must enqueue WP's jQuery, or CDN. It is available to logged in users, but should be noted that out-of-box it is not available on the front-end for logged out users, therefore has to be enqueue'd in the theme.

You pretty much responded to the same affect @renestalder , and just wanted to restate in case somebody else was confused :)

Thank you, and appreciate your time!

**Comment by renestalder** [comment]
Ah, yeah, you are right. It's there because of the admin area, but not automatically in the front-end by default.
